<?php

use CRM_Eventbrite_ExtensionUtil as E;

return array(
  'eventbrite_api_token' => array(
    'group_name' => 'Eventbrite Settings',
    'group' => 'eventbrite',
    'name' => 'eventbrite_api_token',
    'type' => 'String',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('See "Creating Your Personal OAuth Token" on the Eventbrite documentation page <a href="https://www.eventbrite.com/platform/docs/authentication" target="blank">Authenticating Your Access to the Eventbrite API</a>.'),
    'title' => E::ts('Eventbrite Personal OAuth Token'),
    'html_type' => 'Text',
    'quick_form_type' => 'Element',
  ),
  'eventbrite_is_debug' => array(
    'group_name' => 'Eventbrite Settings',
    'group' => 'eventbrite',
    'name' => 'eventbrite_is_debug',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Preserve queue entries for repeat processing.'),
    'title' => E::ts('Enable Queue Debugging'),
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => 0,
    'html_type' => 'radio',
  ),
  'eventbrite_is_link_inspect' => array(
    'group_name' => 'Eventbrite Settings',
    'group' => 'eventbrite',
    'name' => 'eventbrite_is_link_inspect',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Display pop-up data on linked entities such as participants and contributions.'),
    'title' => E::ts('Enable Link Inspection'),
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => 0,
    'html_type' => 'radio',
  ),
  'eventbrite_api_organization_id' => array(
    'group_name' => 'Eventbrite Settings',
    'group' => 'eventbrite',
    'name' => 'eventbrite_api_organization_id',
    'type' => 'String',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Eventbrite system ID for the Eventbrite organization to which all linked events will belong.'),
    'title' => E::ts('Eventbrite API Organization ID'),
    'html_type' => 'Text',
    // Omitting this line causes the setting to be omitted from the Settings form:
    // 'quick_form_type' => 'Element',
    'description' => '',
  ),
);
